rem echo off
git init
git add Bind1/App.xaml
git add Bind1/App.xaml.cs
git add Bind1/ViewModel.cs
git add Bind1/Converters/ConverterBase.cs
git add Bind1/Converters/MyValueConverter.cs
git add Bind1/App.config
git add Bind1/MainWindow.xaml
git add Bind1/MainWindow.xaml.cs
git add Bind1/Properties/AssemblyInfo.cs
git add Bind1/app.config
git add Bind1/Properties/Settings.settings
git add Bind1/Properties/Resources.Designer.cs
git add Bind1/Properties/Resources.resx
git add Bind1/Properties/Settings.Designer.cs
git add Bind1/Bind1.csproj
git add Bind1.sln
git add .gitignore
